In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


pd.set_option('display.max_rows', None)

We will call the **cleaned dataset** from the previous data that we cleaned.

In [ ]:
df= pd.read_csv('/content/cleaned_data_.csv')

print(df.shape)
df.head()

(47560, 338)

/tmp/ipykernel_634/730758599.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('/content/cleaned_data_.csv')

,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,PropertyType,...,District__West Covina Unified School District,District__Western Placer Unified School District,District__Willits Unified School District,District__Willows Unified School District,District__Windsor Unified School District,District__Wiseburn Unified School District,District__Woodland Joint Unified School District,District__Yosemite Unified School District,District__Yuba City Unified School District,District__Yucaipa-Calimesa Joint Unified School District
0,1,NaN,NaN,0,890000.0,Matt,Trudell,34.180411,-118.342020,Residential,...,False,False,False,False,False,False,False,False,False,False
1,0,NaN,NaN,0,1138000.0,Karen,Alvarez,32.574359,-117.023836,Residential,...,False,False,False,False,False,False,False,False,False,False
2,1,NaN,NaN,0,681877.0,Kelly,McLaren,33.725080,-117.222302,Residential,...,False,False,False,False,False,False,False,False,False,False
3,1,NaN,NaN,0,900000.0,Margaret,Bowles,34.203479,-118.643567,Residential,...,False,False,False,False,False,False,False,False,False,False
4,0,NaN,NaN,0,862000.0,Daniel,Cassese,34.460368,-118.490755,Residential,...,False,False,False,False,False,False,False,False,False,False

Let's check what features we have in this cleaned dataset.

In [ ]:
for col in df.columns:
    print(col)

ViewYN
WaterfrontYN
BasementYN
PoolPrivateYN
ClosePrice
ListAgentFirstName
ListAgentLastName
Latitude
Longitude
PropertyType
LivingArea
CoListOfficeName
ListAgentFullName
FireplacesTotal
AssociationFeeFrequency
AboveGradeFinishedArea
TaxAnnualAmount
CountyOrParish
ElementarySchool
AttachedGarageYN
ParkingTotal
BuilderName
PropertySubType
SubdivisionName
BathroomsTotalInteger
City
TaxYear
BuildingAreaTotal
BedroomsTotal
ElementarySchoolDistrict
CoveredSpaces
MiddleOrJuniorSchool
FireplaceYN
Stories
HighSchool
Levels
NewConstructionYN
GarageSpaces
HighSchoolDistrict
PostalCode
AssociationFee
LotSizeSquareFeet
MiddleOrJuniorSchoolDistrict
SalesTaxRate
UnemploymentRate
MortgageRate30Fixed
FedInterestRate
CPI
Age
LotDensity
Flooring_Bamboo
Flooring_Brick
Flooring_Carpet
Flooring_Concrete
Flooring_Laminate
Flooring_SeeRemarks
Flooring_Stone
Flooring_Tile
Flooring_Unknown
Flooring_Vinyl
Flooring_Wood
District__ABC Unified School District
District__Acton-Agua Dulce Unified School District
District__Alameda City Unified School District
District__Albany City Unified School District
District__Alhambra Unified School District
District__Alvord Unified School District
District__Amador County Unified School District
District__Antioch Unified School District
District__Apple Valley Unified School District
District__Arcadia Unified School District
District__Atascadero Unified School District
District__Azusa Unified School District
District__Baldwin Park Unified School District
District__Banning Unified School District
District__Barstow Unified School District
District__Bassett Unified School District
District__Bear Valley Unified School District
District__Beaumont Unified School District
District__Bellflower Unified School District
District__Benicia Unified School District
District__Berkeley Unified School District
District__Beverly Hills Unified School District
District__Big Oak Flat-Groveland Unified School District
District__Biggs Unified School District
District__Bonita Unified School District
District__Bonsall Unified School District
District__Borrego Springs Unified School District
District__Brea-Olinda Unified School District
District__Burbank Unified School District
District__Cabrillo Unified School District
District__Calaveras Unified School District
District__Capistrano Unified School District
District__Carlsbad Unified School District
District__Carpinteria Unified School District
District__Caruthers Unified School District
District__Castro Valley Unified School District
District__Center Joint Unified School District
District__Central Unified School District
District__Ceres Unified School District
District__Charter Oak Unified School District
District__Chawanakee Unified School District
District__Chico Unified School District
District__Chino Valley Unified School District
District__Claremont Unified School District
District__Cloverdale Unified School District
District__Clovis Unified School District
District__Coachella Valley Unified School District
District__Coalinga-Huron Unified School District
District__Coast Unified School District
District__Colton Joint Unified School District
District__Colusa Unified School District
District__Compton Unified School District
District__Conejo Valley Unified School District
District__Corona-Norco Unified School District
District__Coronado Unified School District
District__Covina-Valley Unified School District
District__Culver City Unified School District
District__Cutler-Orosi Joint Unified School District
District__Cuyama Joint Unified School District
District__Davis Joint Unified School District
District__Delhi Unified School District
District__Denair Unified School District
District__Desert Sands Unified School District
District__Dinuba Unified School District
District__Dixon Unified School District
District__Downey Unified School District
District__Duarte Unified School District
District__Dublin Unified School District
District__Durham Unified School District
District__El Rancho Unified School District
District__El Segundo Unified School District
District__El Tejon Unified School District
District__Elk Grove Unified School District
District__Emery Unified School District
District__Escalon Unified School District
District__Fairfield-Suisun Unified School District
District__Fillmore Unified School District
District__Firebaugh-Las Deltas Unified School District
District__Folsom-Cordova Unified School District
District__Fontana Unified School District
District__Fort Bragg Unified School District
District__Fowler Unified School District
District__Fremont Unified School District
District__Fresno Unified School District
District__Garden Grove Unified School District
District__Gateway Unified School District
District__Gilroy Unified School District
District__Glendale Unified School District
District__Glendora Unified School District
District__Golden Plains Unified School District
District__Golden Valley Unified School District
District__Gridley Unified School District
District__Gustine Unified School District
District__Hacienda La Puente Unified School District
District__Hamilton Unified School District
District__Hayward Unified School District
District__Hemet Unified School District
District__Hesperia Unified School District
District__Hilmar Unified School District
District__Holtville Unified School District
District__Hughson Unified School District
District__Imperial Unified School District
District__Inglewood Unified School District
District__Irvine Unified School District
District__John Swett Unified School District
District__Jurupa Unified School District
District__Kelseyville Unified School District
District__Kings Canyon Joint Unified School District
District__Konocti Unified School District
District__La CaÃ±ada Unified School District
District__Laguna Beach Unified School District
District__Lake Elsinore Unified School District
District__Lake Tahoe Unified School District
District__Lakeport Unified School District
District__Lammersville Joint Unified School District
District__Las Virgenes Unified School District
District__Lincoln Unified School District
District__Live Oak Unified School District
District__Livermore Valley Joint Unified School District
District__Lodi Unified School District
District__Lompoc Unified School District
District__Long Beach Unified School District
District__Los Alamitos Unified School District
District__Los Angeles Unified School District
District__Los Banos Unified School District
District__Los Molinos Unified School District
District__Lucerne Valley Unified School District
District__Lucia Mar Unified School District
District__Lynwood Unified School District
District__Madera Unified School District
District__Mammoth Unified School District
District__Manhattan Beach Unified School District
District__Manteca Unified School District
District__Maricopa Unified School District
District__Mariposa County Unified School District
District__Martinez Unified School District
District__Marysville Joint Unified School District
District__Mendocino Unified School District
District__Middletown Unified School District
District__Milpitas Unified School District
District__Mojave Unified School District
District__Monrovia Unified School District
District__Montebello Unified School District
District__Monterey Peninsula Unified School District
District__Moorpark Unified School District
District__Moreno Valley Unified School District
District__Morgan Hill Unified School District
District__Morongo Unified School District
District__Mount Diablo Unified School District
District__Mountain Empire Unified School District
District__Muroc Joint Unified School District
District__Murrieta Valley Unified School District
District__Napa Valley Unified School District
District__Natomas Unified School District
District__Needles Unified School District
District__New Haven Unified School District
District__Newark Unified School District
District__Newman-Crows Landing Unified School District
District__Newport-Mesa Unified School District
District__North Monterey County Unified School District
District__Norwalk-La Mirada Unified School District
District__Novato Unified School District
District__Oak Park Unified School District
District__Oakdale Joint Unified School District
District__Oakland Unified School District
District__Oceanside Unified School District
District__Ojai Unified School District
District__Orange Unified School District
District__Orland Joint Unified School District
District__Pacific Grove Unified School District
District__Pajaro Valley Joint Unified School District
District__Palm Springs Unified School District
District__Palo Alto Unified School District
District__Palo Verde Unified School District
District__Palos Verdes Peninsula Unified School District
District__Paradise Unified School District
District__Paramount Unified School District
District__Pasadena Unified School District
District__Paso Robles Joint Unified School District
District__Patterson Joint Unified School District
District__Piedmont City Unified School District
District__Pittsburg Unified School District
District__Placentia-Yorba Linda Unified School District
District__Pleasanton Unified School District
District__Plumas Unified School District
District__Pomona Unified School District
District__Porterville Unified School District
District__Poway Unified School District
District__Princeton Joint Unified School District
District__Ramona City Unified School District
District__Redlands Unified School District
District__Redondo Beach Unified School District
District__Reef-Sunset Unified School District
District__Rialto Unified School District
District__Rim of the World Unified School District
District__Ripon Unified School District
District__River Delta Joint Unified School District
District__Riverbank Unified School District
District__Riverdale Joint Unified School District
District__Riverside Unified School District
District__Rocklin Unified School District
District__Rowland Unified School District
District__Sacramento City Unified School District
District__Saddleback Valley Unified School District
District__San Bernardino City Unified School District
District__San Diego City Unified School District
District__San Francisco Unified School District
District__San Gabriel Unified School District
District__San Jacinto Unified School District
District__San Jose Unified School District
District__San Juan Unified School District
District__San Leandro Unified School District
District__San Lorenzo Unified School District
District__San Lorenzo Valley Unified School District
District__San Luis Coastal Unified School District
District__San Marcos Unified School District
District__San Marino Unified School District
District__San Ramon Valley Unified School District
District__Sanger Unified School District
District__Santa Ana Unified School District
District__Santa Barbara Unified School District
District__Santa Clara Unified School District
District__Santa Monica-Malibu Unified School District
District__Santa Paula Unified School District
District__Selma Unified School District
District__Shandon Joint Unified School District
District__Shoreline Unified School District
District__Sierra Sands Unified School District
District__Sierra Unified School District
District__Silver Valley Unified School District
District__Simi Valley Unified School District
District__Snowline Joint Unified School District
District__Soledad Unified School District
District__Sonoma Valley Unified School District
District__South Pasadena Unified School District
District__South San Francisco Unified School District
District__Southern Kern Unified School District
District__Stockton Unified School District
District__Sunol Glen Unified School District
District__Tahoe-Truckee Unified School District
District__Tehachapi Unified School District
District__Temecula Valley Unified School District
District__Temple City Unified School District
District__Templeton Unified School District
District__Torrance Unified School District
District__Tracy Unified School District
District__Travis Unified School District
District__Trinity Alps Unified School District
District__Turlock Unified School District
District__Tustin Unified School District
District__Twin Rivers Unified School District
District__Ukiah Unified School District
District__Unknown
District__Upland Unified School District
District__Upper Lake Unified School District
District__Vacaville Unified School District
District__Val Verde Unified School District
District__Vallejo City Unified School District
District__Valley Center-Pauma Unified School District
District__Ventura Unified School District
District__Visalia Unified School District
District__Vista Unified School District
District__Walnut Valley Unified School District
District__Warner Unified School District
District__Washington Unified School District
District__Waterford Unified School District
District__West Contra Costa Unified School District
District__West Covina Unified School District
District__Western Placer Unified School District
District__Willits Unified School District
District__Willows Unified School District
District__Windsor Unified School District
District__Wiseburn Unified School District
District__Woodland Joint Unified School District
District__Yosemite Unified School District
District__Yuba City Unified School District
District__Yucaipa-Calimesa Joint Unified School District

We can see that there is many District_ features and Flooring_ features described as dummies variables.

Let's bring the dummies variables into regular variables combining into one variable on Flooring_ and District_

In [ ]:
flooring= []

# scan all features starting with Flooring_ and put in flooring set
for col in df.columns:
  if col.startswith("Flooring_"):
    flooring.append(col)

# apply flooring data into original dataset naming FlooringType
df["FlooringType"]=df[flooring].apply(lambda x: x.idxmax(), axis=1)
df["FlooringType"] = df["FlooringType"].str.replace("Flooring_", "")

# delete all the features that starts with Flooring_ in original dataset
df=df.drop(columns=flooring)

Let's double check.

In [ ]:
for col in df.columns:
    print(col)

ViewYN
WaterfrontYN
BasementYN
PoolPrivateYN
ClosePrice
ListAgentFirstName
ListAgentLastName
Latitude
Longitude
PropertyType
LivingArea
CoListOfficeName
ListAgentFullName
FireplacesTotal
AssociationFeeFrequency
AboveGradeFinishedArea
TaxAnnualAmount
CountyOrParish
ElementarySchool
AttachedGarageYN
ParkingTotal
BuilderName
PropertySubType
SubdivisionName
BathroomsTotalInteger
City
TaxYear
BuildingAreaTotal
BedroomsTotal
ElementarySchoolDistrict
CoveredSpaces
MiddleOrJuniorSchool
FireplaceYN
Stories
HighSchool
Levels
NewConstructionYN
GarageSpaces
HighSchoolDistrict
PostalCode
AssociationFee
LotSizeSquareFeet
MiddleOrJuniorSchoolDistrict
SalesTaxRate
UnemploymentRate
MortgageRate30Fixed
FedInterestRate
CPI
Age
LotDensity
District__ABC Unified School District
District__Acton-Agua Dulce Unified School District
District__Alameda City Unified School District
District__Albany City Unified School District
District__Alhambra Unified School District
District__Alvord Unified School District
District__Amador County Unified School District
District__Antioch Unified School District
District__Apple Valley Unified School District
District__Arcadia Unified School District
District__Atascadero Unified School District
District__Azusa Unified School District
District__Baldwin Park Unified School District
District__Banning Unified School District
District__Barstow Unified School District
District__Bassett Unified School District
District__Bear Valley Unified School District
District__Beaumont Unified School District
District__Bellflower Unified School District
District__Benicia Unified School District
District__Berkeley Unified School District
District__Beverly Hills Unified School District
District__Big Oak Flat-Groveland Unified School District
District__Biggs Unified School District
District__Bonita Unified School District
District__Bonsall Unified School District
District__Borrego Springs Unified School District
District__Brea-Olinda Unified School District
District__Burbank Unified School District
District__Cabrillo Unified School District
District__Calaveras Unified School District
District__Capistrano Unified School District
District__Carlsbad Unified School District
District__Carpinteria Unified School District
District__Caruthers Unified School District
District__Castro Valley Unified School District
District__Center Joint Unified School District
District__Central Unified School District
District__Ceres Unified School District
District__Charter Oak Unified School District
District__Chawanakee Unified School District
District__Chico Unified School District
District__Chino Valley Unified School District
District__Claremont Unified School District
District__Cloverdale Unified School District
District__Clovis Unified School District
District__Coachella Valley Unified School District
District__Coalinga-Huron Unified School District
District__Coast Unified School District
District__Colton Joint Unified School District
District__Colusa Unified School District
District__Compton Unified School District
District__Conejo Valley Unified School District
District__Corona-Norco Unified School District
District__Coronado Unified School District
District__Covina-Valley Unified School District
District__Culver City Unified School District
District__Cutler-Orosi Joint Unified School District
District__Cuyama Joint Unified School District
District__Davis Joint Unified School District
District__Delhi Unified School District
District__Denair Unified School District
District__Desert Sands Unified School District
District__Dinuba Unified School District
District__Dixon Unified School District
District__Downey Unified School District
District__Duarte Unified School District
District__Dublin Unified School District
District__Durham Unified School District
District__El Rancho Unified School District
District__El Segundo Unified School District
District__El Tejon Unified School District
District__Elk Grove Unified School District
District__Emery Unified School District
District__Escalon Unified School District
District__Fairfield-Suisun Unified School District
District__Fillmore Unified School District
District__Firebaugh-Las Deltas Unified School District
District__Folsom-Cordova Unified School District
District__Fontana Unified School District
District__Fort Bragg Unified School District
District__Fowler Unified School District
District__Fremont Unified School District
District__Fresno Unified School District
District__Garden Grove Unified School District
District__Gateway Unified School District
District__Gilroy Unified School District
District__Glendale Unified School District
District__Glendora Unified School District
District__Golden Plains Unified School District
District__Golden Valley Unified School District
District__Gridley Unified School District
District__Gustine Unified School District
District__Hacienda La Puente Unified School District
District__Hamilton Unified School District
District__Hayward Unified School District
District__Hemet Unified School District
District__Hesperia Unified School District
District__Hilmar Unified School District
District__Holtville Unified School District
District__Hughson Unified School District
District__Imperial Unified School District
District__Inglewood Unified School District
District__Irvine Unified School District
District__John Swett Unified School District
District__Jurupa Unified School District
District__Kelseyville Unified School District
District__Kings Canyon Joint Unified School District
District__Konocti Unified School District
District__La CaÃ±ada Unified School District
District__Laguna Beach Unified School District
District__Lake Elsinore Unified School District
District__Lake Tahoe Unified School District
District__Lakeport Unified School District
District__Lammersville Joint Unified School District
District__Las Virgenes Unified School District
District__Lincoln Unified School District
District__Live Oak Unified School District
District__Livermore Valley Joint Unified School District
District__Lodi Unified School District
District__Lompoc Unified School District
District__Long Beach Unified School District
District__Los Alamitos Unified School District
District__Los Angeles Unified School District
District__Los Banos Unified School District
District__Los Molinos Unified School District
District__Lucerne Valley Unified School District
District__Lucia Mar Unified School District
District__Lynwood Unified School District
District__Madera Unified School District
District__Mammoth Unified School District
District__Manhattan Beach Unified School District
District__Manteca Unified School District
District__Maricopa Unified School District
District__Mariposa County Unified School District
District__Martinez Unified School District
District__Marysville Joint Unified School District
District__Mendocino Unified School District
District__Middletown Unified School District
District__Milpitas Unified School District
District__Mojave Unified School District
District__Monrovia Unified School District
District__Montebello Unified School District
District__Monterey Peninsula Unified School District
District__Moorpark Unified School District
District__Moreno Valley Unified School District
District__Morgan Hill Unified School District
District__Morongo Unified School District
District__Mount Diablo Unified School District
District__Mountain Empire Unified School District
District__Muroc Joint Unified School District
District__Murrieta Valley Unified School District
District__Napa Valley Unified School District
District__Natomas Unified School District
District__Needles Unified School District
District__New Haven Unified School District
District__Newark Unified School District
District__Newman-Crows Landing Unified School District
District__Newport-Mesa Unified School District
District__North Monterey County Unified School District
District__Norwalk-La Mirada Unified School District
District__Novato Unified School District
District__Oak Park Unified School District
District__Oakdale Joint Unified School District
District__Oakland Unified School District
District__Oceanside Unified School District
District__Ojai Unified School District
District__Orange Unified School District
District__Orland Joint Unified School District
District__Pacific Grove Unified School District
District__Pajaro Valley Joint Unified School District
District__Palm Springs Unified School District
District__Palo Alto Unified School District
District__Palo Verde Unified School District
District__Palos Verdes Peninsula Unified School District
District__Paradise Unified School District
District__Paramount Unified School District
District__Pasadena Unified School District
District__Paso Robles Joint Unified School District
District__Patterson Joint Unified School District
District__Piedmont City Unified School District
District__Pittsburg Unified School District
District__Placentia-Yorba Linda Unified School District
District__Pleasanton Unified School District
District__Plumas Unified School District
District__Pomona Unified School District
District__Porterville Unified School District
District__Poway Unified School District
District__Princeton Joint Unified School District
District__Ramona City Unified School District
District__Redlands Unified School District
District__Redondo Beach Unified School District
District__Reef-Sunset Unified School District
District__Rialto Unified School District
District__Rim of the World Unified School District
District__Ripon Unified School District
District__River Delta Joint Unified School District
District__Riverbank Unified School District
District__Riverdale Joint Unified School District
District__Riverside Unified School District
District__Rocklin Unified School District
District__Rowland Unified School District
District__Sacramento City Unified School District
District__Saddleback Valley Unified School District
District__San Bernardino City Unified School District
District__San Diego City Unified School District
District__San Francisco Unified School District
District__San Gabriel Unified School District
District__San Jacinto Unified School District
District__San Jose Unified School District
District__San Juan Unified School District
District__San Leandro Unified School District
District__San Lorenzo Unified School District
District__San Lorenzo Valley Unified School District
District__San Luis Coastal Unified School District
District__San Marcos Unified School District
District__San Marino Unified School District
District__San Ramon Valley Unified School District
District__Sanger Unified School District
District__Santa Ana Unified School District
District__Santa Barbara Unified School District
District__Santa Clara Unified School District
District__Santa Monica-Malibu Unified School District
District__Santa Paula Unified School District
District__Selma Unified School District
District__Shandon Joint Unified School District
District__Shoreline Unified School District
District__Sierra Sands Unified School District
District__Sierra Unified School District
District__Silver Valley Unified School District
District__Simi Valley Unified School District
District__Snowline Joint Unified School District
District__Soledad Unified School District
District__Sonoma Valley Unified School District
District__South Pasadena Unified School District
District__South San Francisco Unified School District
District__Southern Kern Unified School District
District__Stockton Unified School District
District__Sunol Glen Unified School District
District__Tahoe-Truckee Unified School District
District__Tehachapi Unified School District
District__Temecula Valley Unified School District
District__Temple City Unified School District
District__Templeton Unified School District
District__Torrance Unified School District
District__Tracy Unified School District
District__Travis Unified School District
District__Trinity Alps Unified School District
District__Turlock Unified School District
District__Tustin Unified School District
District__Twin Rivers Unified School District
District__Ukiah Unified School District
District__Unknown
District__Upland Unified School District
District__Upper Lake Unified School District
District__Vacaville Unified School District
District__Val Verde Unified School District
District__Vallejo City Unified School District
District__Valley Center-Pauma Unified School District
District__Ventura Unified School District
District__Visalia Unified School District
District__Vista Unified School District
District__Walnut Valley Unified School District
District__Warner Unified School District
District__Washington Unified School District
District__Waterford Unified School District
District__West Contra Costa Unified School District
District__West Covina Unified School District
District__Western Placer Unified School District
District__Willits Unified School District
District__Willows Unified School District
District__Windsor Unified School District
District__Wiseburn Unified School District
District__Woodland Joint Unified School District
District__Yosemite Unified School District
District__Yuba City Unified School District
District__Yucaipa-Calimesa Joint Unified School District
FlooringType

Now we will do same work on District_ features as what we did above.

In [ ]:
District = []

# scan all the District_ features in orginal dataset and put in District set
for col in df.columns:
  if col.startswith("District_"):
    District.append(col)

# put all those features in one feature called SchoolDistrict
df["SchoolDistrict"]=df[District].apply(lambda x: x.idxmax(), axis=1)
df["SchoolDistrict"] = df["SchoolDistrict"].str.replace("Flooring_", "")

# delete the features starts with District_
df=df.drop(columns=District)

In [ ]:
for col in df.columns:
    print(col)

ViewYN
WaterfrontYN
BasementYN
PoolPrivateYN
ClosePrice
ListAgentFirstName
ListAgentLastName
Latitude
Longitude
PropertyType
LivingArea
CoListOfficeName
ListAgentFullName
FireplacesTotal
AssociationFeeFrequency
AboveGradeFinishedArea
TaxAnnualAmount
CountyOrParish
ElementarySchool
AttachedGarageYN
ParkingTotal
BuilderName
PropertySubType
SubdivisionName
BathroomsTotalInteger
City
TaxYear
BuildingAreaTotal
BedroomsTotal
ElementarySchoolDistrict
CoveredSpaces
MiddleOrJuniorSchool
FireplaceYN
Stories
HighSchool
Levels
NewConstructionYN
GarageSpaces
HighSchoolDistrict
PostalCode
AssociationFee
LotSizeSquareFeet
MiddleOrJuniorSchoolDistrict
SalesTaxRate
UnemploymentRate
MortgageRate30Fixed
FedInterestRate
CPI
Age
LotDensity
FlooringType
SchoolDistrict

In [ ]:
df["SchoolDistrict"].value_counts()

SchoolDistrict
District__Unknown                                           11309
District__Los Angeles Unified School District                4103
District__San Diego City Unified School District             1226
District__Capistrano Unified School District                  995
District__Desert Sands Unified School District                963
District__Corona-Norco Unified School District                794
District__Palm Springs Unified School District                729
District__Riverside Unified School District                   713
District__Hemet Unified School District                       673
District__Long Beach Unified School District                  628
District__Temecula Valley Unified School District             614
District__Oakland Unified School District                     595
District__San Bernardino City Unified School District         543
District__Lake Elsinore Unified School District               534
District__Mount Diablo Unified School District                529
District__Saddleback Valley Unified School District           478
District__Moreno Valley Unified School District               461
District__Orange Unified School District                      444
District__Hesperia Unified School District                    442
District__Apple Valley Unified School District                425
District__Beaumont Unified School District                    411
District__Chino Valley Unified School District                407
District__Murrieta Valley Unified School District             402
District__Redlands Unified School District                    388
District__Vista Unified School District                       359
District__Conejo Valley Unified School District               352
District__Simi Valley Unified School District                 350
District__West Contra Costa Unified School District           347
District__Poway Unified School District                       347
District__San Ramon Valley Unified School District            342
District__Newport-Mesa Unified School District                341
District__Morongo Unified School District                     332
District__Fontana Unified School District                     327
District__Placentia-Yorba Linda Unified School District       324
District__Chico Unified School District                       321
District__Pasadena Unified School District                    297
District__Garden Grove Unified School District                287
District__Coachella Valley Unified School District            284
District__Irvine Unified School District                      282
District__Antioch Unified School District                     281
District__Bear Valley Unified School District                 258
District__Livermore Valley Joint Unified School District      248
District__Torrance Unified School District                    243
District__Rialto Unified School District                      239
District__Ventura Unified School District                     236
District__Rim of the World Unified School District            235
District__Pomona Unified School District                      235
District__Lucia Mar Unified School District                   234
District__San Marcos Unified School District                  232
District__Oceanside Unified School District                   229
District__San Luis Coastal Unified School District            222
District__Norwalk-La Mirada Unified School District           221
District__Jurupa Unified School District                      214
District__Fremont Unified School District                     208
District__Glendale Unified School District                    207
District__Tustin Unified School District                      206
District__Yucaipa-Calimesa Joint Unified School District      204
District__Snowline Joint Unified School District              194
District__Val Verde Unified School District                   188
District__Hacienda La Puente Unified School District          185
District__San Jacinto Unified School District                 183
District__Upland Unified School District                      181
District__Compton Unified School District                     178
District__Palos Verdes Peninsula Unified School District      177
District__Alvord Unified School District                      176
District__Carlsbad Unified School District                    173
District__Las Virgenes Unified School District                168
District__Hayward Unified School District                     165
District__Banning Unified School District                     164
District__Colton Joint Unified School District                160
District__Pleasanton Unified School District                  159
District__Burbank Unified School District                     158
District__Rowland Unified School District                     153
District__Downey Unified School District                      148
District__Paso Robles Joint Unified School District           141
District__ABC Unified School District                         138
District__Berkeley Unified School District                    138
District__Santa Ana Unified School District                   136
District__Covina-Valley Unified School District               128
District__Bonita Unified School District                      127
District__Paradise Unified School District                    124
District__Walnut Valley Unified School District               124
District__Bellflower Unified School District                  123
District__Claremont Unified School District                   114
District__Brea-Olinda Unified School District                 107
District__Ramona City Unified School District                 107
District__Glendora Unified School District                    106
District__Alhambra Unified School District                    102
District__Vallejo City Unified School District                101
District__Valley Center-Pauma Unified School District         100
District__West Covina Unified School District                  98
District__San Lorenzo Unified School District                  97
District__Pittsburg Unified School District                    96
District__Azusa Unified School District                        96
District__Montebello Unified School District                   95
District__Dublin Unified School District                       91
District__Los Alamitos Unified School District                 91
District__Redondo Beach Unified School District                90
District__Arcadia Unified School District                      89
District__Atascadero Unified School District                   89
District__Alameda City Unified School District                 87
District__Manhattan Beach Unified School District              85
District__Castro Valley Unified School District                82
District__Clovis Unified School District                       80
District__Southern Kern Unified School District                78
District__San Leandro Unified School District                  78
District__Moorpark Unified School District                     77
District__Fresno Unified School District                       77
District__Bonsall Unified School District                      74
District__Barstow Unified School District                      74
District__Monrovia Unified School District                     74
District__Manteca Unified School District                      74
District__New Haven Unified School District                    73
District__Charter Oak Unified School District                  71
District__Laguna Beach Unified School District                 70
District__El Rancho Unified School District                    69
District__El Tejon Unified School District                     68
District__Martinez Unified School District                     66
District__Inglewood Unified School District                    66
District__Baldwin Park Unified School District                 60
District__Ojai Unified School District                         60
District__Newark Unified School District                       60
District__Middletown Unified School District                   55
District__Fairfield-Suisun Unified School District             53
District__San Gabriel Unified School District                  51
District__Duarte Unified School District                       51
District__Santa Monica-Malibu Unified School District          49
District__La CaÃ±ada Unified School District                   47
District__Konocti Unified School District                      47
District__Madera Unified School District                       47
District__Kelseyville Unified School District                  47
District__Santa Paula Unified School District                  45
District__Mojave Unified School District                       45
District__South Pasadena Unified School District               44
District__Fillmore Unified School District                     42
District__Paramount Unified School District                    42
District__Tehachapi Unified School District                    41
District__Oak Park Unified School District                     40
District__Tracy Unified School District                        38
District__Temple City Unified School District                  37
District__Stockton Unified School District                     37
District__San Marino Unified School District                   37
District__Elk Grove Unified School District                    36
District__Coast Unified School District                        36
District__Lompoc Unified School District                       35
District__Bassett Unified School District                      35
District__Mountain Empire Unified School District              35
District__Los Banos Unified School District                    33
District__Culver City Unified School District                  33
District__Vacaville Unified School District                    33
District__Lakeport Unified School District                     31
District__Yosemite Unified School District                     31
District__Coronado Unified School District                     31
District__El Segundo Unified School District                   30
District__Fort Bragg Unified School District                   30
District__Orland Joint Unified School District                 29
District__Visalia Unified School District                      29
District__Lucerne Valley Unified School District               28
District__Sacramento City Unified School District              28
District__San Juan Unified School District                     27
District__Lammersville Joint Unified School District           27
District__Borrego Springs Unified School District              25
District__Central Unified School District                      25
District__Lynwood Unified School District                      25
District__Acton-Agua Dulce Unified School District             24
District__John Swett Unified School District                   24
District__Willows Unified School District                      24
District__Piedmont City Unified School District                23
District__San Francisco Unified School District                23
District__Wiseburn Unified School District                     23
District__San Jose Unified School District                     23
District__Twin Rivers Unified School District                  23
District__Travis Unified School District                       22
District__Turlock Unified School District                      22
District__Lodi Unified School District                         22
District__Mariposa County Unified School District              21
District__Albany City Unified School District                  20
District__River Delta Joint Unified School District            20
District__Templeton Unified School District                    18
District__Marysville Joint Unified School District             16
District__Santa Barbara Unified School District                15
District__Patterson Joint Unified School District              15
District__Palo Verde Unified School District                   15
District__Chawanakee Unified School District                   14
District__Yuba City Unified School District                    14
District__Golden Valley Unified School District                13
District__Morgan Hill Unified School District                  12
District__Santa Clara Unified School District                  12
District__Napa Valley Unified School District                  11
District__Gridley Unified School District                      11
District__Coalinga-Huron Unified School District               11
District__Sierra Sands Unified School District                 10
District__Milpitas Unified School District                     10
District__Mendocino Unified School District                     9
District__Benicia Unified School District                       9
District__South San Francisco Unified School District           8
District__Beverly Hills Unified School District                 8
District__Kings Canyon Joint Unified School District            8
District__Natomas Unified School District                       8
District__Sanger Unified School District                        7
District__Durham Unified School District                        7
District__Newman-Crows Landing Unified School District          7
District__Shandon Joint Unified School District                 6
District__Carpinteria Unified School District                   6
District__Folsom-Cordova Unified School District                6
District__Western Placer Unified School District                6
District__Delhi Unified School District                         6
District__Gilroy Unified School District                        6
District__Los Molinos Unified School District                   6
District__Lincoln Unified School District                       6
District__Imperial Unified School District                      6
District__Novato Unified School District                        5
District__Gustine Unified School District                       5
District__Fowler Unified School District                        4
District__Trinity Alps Unified School District                  4
District__Center Joint Unified School District                  4
District__Oakdale Joint Unified School District                 4
District__Plumas Unified School District                        4
District__Hilmar Unified School District                        4
District__Washington Unified School District                    4
District__Monterey Peninsula Unified School District            4
District__Warner Unified School District                        3
District__Selma Unified School District                         3
District__Amador County Unified School District                 3
District__Upper Lake Unified School District                    3
District__Rocklin Unified School District                       3
District__Lake Tahoe Unified School District                    3
District__Biggs Unified School District                         3
District__Hughson Unified School District                       3
District__Colusa Unified School District                        3
District__Windsor Unified School District                       3
District__Pajaro Valley Joint Unified School District           3
District__Willits Unified School District                       3
District__Maricopa Unified School District                      3
District__Calaveras Unified School District                     3
District__Escalon Unified School District                       3
District__Ukiah Unified School District                         3
District__Sierra Unified School District                        3
District__Silver Valley Unified School District                 3
District__Riverbank Unified School District                     2
District__Ceres Unified School District                         2
District__Emery Unified School District                         2
District__Golden Plains Unified School District                 2
District__Cabrillo Unified School District                      2
District__San Lorenzo Valley Unified School District            2
District__Ripon Unified School District                         2
District__Big Oak Flat-Groveland Unified School District        2
District__Live Oak Unified School District                      2
District__Caruthers Unified School District                     2
District__Palo Alto Unified School District                     2
District__Needles Unified School District                       2
District__Reef-Sunset Unified School District                   1
District__Gateway Unified School District                       1
District__Porterville Unified School District                   1
District__Cutler-Orosi Joint Unified School District            1
District__Hamilton Unified School District                      1
District__Dinuba Unified School District                        1
District__Soledad Unified School District                       1
District__Holtville Unified School District                     1
District__Cuyama Joint Unified School District                  1
District__Waterford Unified School District                     1
District__Pacific Grove Unified School District                 1
District__Sunol Glen Unified School District                    1
District__Woodland Joint Unified School District                1
District__Tahoe-Truckee Unified School District                 1
District__Dixon Unified School District                         1
District__Princeton Joint Unified School District               1
District__Muroc Joint Unified School District                   1
District__Mammoth Unified School District                       1
District__Cloverdale Unified School District                    1
District__Shoreline Unified School District                     1
District__Sonoma Valley Unified School District                 1
District__Denair Unified School District                        1
District__North Monterey County Unified School District         1
District__Davis Joint Unified School District                   1
District__Firebaugh-Las Deltas Unified School District          1
District__Riverdale Joint Unified School District               1
Name: count, dtype: int64

We will remove the values that listed "District_" and "School District" in each values.

In [ ]:
#Take off "District_"
df["SchoolDistrict"] = (df["SchoolDistrict"].str.replace("District__", '').str.replace(r"\s+School District", "",regex=True).str.strip())

count_district=df["SchoolDistrict"].value_counts()
count_district

SchoolDistrict
Unknown                           11309
Los Angeles Unified                4103
San Diego City Unified             1226
Capistrano Unified                  995
Desert Sands Unified                963
Corona-Norco Unified                794
Palm Springs Unified                729
Riverside Unified                   713
Hemet Unified                       673
Long Beach Unified                  628
Temecula Valley Unified             614
Oakland Unified                     595
San Bernardino City Unified         543
Lake Elsinore Unified               534
Mount Diablo Unified                529
Saddleback Valley Unified           478
Moreno Valley Unified               461
Orange Unified                      444
Hesperia Unified                    442
Apple Valley Unified                425
Beaumont Unified                    411
Chino Valley Unified                407
Murrieta Valley Unified             402
Redlands Unified                    388
Vista Unified                       359
Conejo Valley Unified               352
Simi Valley Unified                 350
West Contra Costa Unified           347
Poway Unified                       347
San Ramon Valley Unified            342
Newport-Mesa Unified                341
Morongo Unified                     332
Fontana Unified                     327
Placentia-Yorba Linda Unified       324
Chico Unified                       321
Pasadena Unified                    297
Garden Grove Unified                287
Coachella Valley Unified            284
Irvine Unified                      282
Antioch Unified                     281
Bear Valley Unified                 258
Livermore Valley Joint Unified      248
Torrance Unified                    243
Rialto Unified                      239
Ventura Unified                     236
Rim of the World Unified            235
Pomona Unified                      235
Lucia Mar Unified                   234
San Marcos Unified                  232
Oceanside Unified                   229
San Luis Coastal Unified            222
Norwalk-La Mirada Unified           221
Jurupa Unified                      214
Fremont Unified                     208
Glendale Unified                    207
Tustin Unified                      206
Yucaipa-Calimesa Joint Unified      204
Snowline Joint Unified              194
Val Verde Unified                   188
Hacienda La Puente Unified          185
San Jacinto Unified                 183
Upland Unified                      181
Compton Unified                     178
Palos Verdes Peninsula Unified      177
Alvord Unified                      176
Carlsbad Unified                    173
Las Virgenes Unified                168
Hayward Unified                     165
Banning Unified                     164
Colton Joint Unified                160
Pleasanton Unified                  159
Burbank Unified                     158
Rowland Unified                     153
Downey Unified                      148
Paso Robles Joint Unified           141
ABC Unified                         138
Berkeley Unified                    138
Santa Ana Unified                   136
Covina-Valley Unified               128
Bonita Unified                      127
Paradise Unified                    124
Walnut Valley Unified               124
Bellflower Unified                  123
Claremont Unified                   114
Brea-Olinda Unified                 107
Ramona City Unified                 107
Glendora Unified                    106
Alhambra Unified                    102
Vallejo City Unified                101
Valley Center-Pauma Unified         100
West Covina Unified                  98
San Lorenzo Unified                  97
Pittsburg Unified                    96
Azusa Unified                        96
Montebello Unified                   95
Dublin Unified                       91
Los Alamitos Unified                 91
Redondo Beach Unified                90
Arcadia Unified                      89
Atascadero Unified                   89
Alameda City Unified                 87
Manhattan Beach Unified              85
Castro Valley Unified                82
Clovis Unified                       80
Southern Kern Unified                78
San Leandro Unified                  78
Moorpark Unified                     77
Fresno Unified                       77
Bonsall Unified                      74
Barstow Unified                      74
Monrovia Unified                     74
Manteca Unified                      74
New Haven Unified                    73
Charter Oak Unified                  71
Laguna Beach Unified                 70
El Rancho Unified                    69
El Tejon Unified                     68
Martinez Unified                     66
Inglewood Unified                    66
Baldwin Park Unified                 60
Ojai Unified                         60
Newark Unified                       60
Middletown Unified                   55
Fairfield-Suisun Unified             53
San Gabriel Unified                  51
Duarte Unified                       51
Santa Monica-Malibu Unified          49
La CaÃ±ada Unified                   47
Konocti Unified                      47
Madera Unified                       47
Kelseyville Unified                  47
Santa Paula Unified                  45
Mojave Unified                       45
South Pasadena Unified               44
Fillmore Unified                     42
Paramount Unified                    42
Tehachapi Unified                    41
Oak Park Unified                     40
Tracy Unified                        38
Temple City Unified                  37
Stockton Unified                     37
San Marino Unified                   37
Elk Grove Unified                    36
Coast Unified                        36
Lompoc Unified                       35
Bassett Unified                      35
Mountain Empire Unified              35
Los Banos Unified                    33
Culver City Unified                  33
Vacaville Unified                    33
Lakeport Unified                     31
Yosemite Unified                     31
Coronado Unified                     31
El Segundo Unified                   30
Fort Bragg Unified                   30
Orland Joint Unified                 29
Visalia Unified                      29
Lucerne Valley Unified               28
Sacramento City Unified              28
San Juan Unified                     27
Lammersville Joint Unified           27
Borrego Springs Unified              25
Central Unified                      25
Lynwood Unified                      25
Acton-Agua Dulce Unified             24
John Swett Unified                   24
Willows Unified                      24
Piedmont City Unified                23
San Francisco Unified                23
Wiseburn Unified                     23
San Jose Unified                     23
Twin Rivers Unified                  23
Travis Unified                       22
Turlock Unified                      22
Lodi Unified                         22
Mariposa County Unified              21
Albany City Unified                  20
River Delta Joint Unified            20
Templeton Unified                    18
Marysville Joint Unified             16
Santa Barbara Unified                15
Patterson Joint Unified              15
Palo Verde Unified                   15
Chawanakee Unified                   14
Yuba City Unified                    14
Golden Valley Unified                13
Morgan Hill Unified                  12
Santa Clara Unified                  12
Napa Valley Unified                  11
Gridley Unified                      11
Coalinga-Huron Unified               11
Sierra Sands Unified                 10
Milpitas Unified                     10
Mendocino Unified                     9
Benicia Unified                       9
South San Francisco Unified           8
Beverly Hills Unified                 8
Kings Canyon Joint Unified            8
Natomas Unified                       8
Sanger Unified                        7
Durham Unified                        7
Newman-Crows Landing Unified          7
Shandon Joint Unified                 6
Carpinteria Unified                   6
Folsom-Cordova Unified                6
Western Placer Unified                6
Delhi Unified                         6
Gilroy Unified                        6
Los Molinos Unified                   6
Lincoln Unified                       6
Imperial Unified                      6
Novato Unified                        5
Gustine Unified                       5
Fowler Unified                        4
Trinity Alps Unified                  4
Center Joint Unified                  4
Oakdale Joint Unified                 4
Plumas Unified                        4
Hilmar Unified                        4
Washington Unified                    4
Monterey Peninsula Unified            4
Warner Unified                        3
Selma Unified                         3
Amador County Unified                 3
Upper Lake Unified                    3
Rocklin Unified                       3
Lake Tahoe Unified                    3
Biggs Unified                         3
Hughson Unified                       3
Colusa Unified                        3
Windsor Unified                       3
Pajaro Valley Joint Unified           3
Willits Unified                       3
Maricopa Unified                      3
Calaveras Unified                     3
Escalon Unified                       3
Ukiah Unified                         3
Sierra Unified                        3
Silver Valley Unified                 3
Riverbank Unified                     2
Ceres Unified                         2
Emery Unified                         2
Golden Plains Unified                 2
Cabrillo Unified                      2
San Lorenzo Valley Unified            2
Ripon Unified                         2
Big Oak Flat-Groveland Unified        2
Live Oak Unified                      2
Caruthers Unified                     2
Palo Alto Unified                     2
Needles Unified                       2
Reef-Sunset Unified                   1
Gateway Unified                       1
Porterville Unified                   1
Cutler-Orosi Joint Unified            1
Hamilton Unified                      1
Dinuba Unified                        1
Soledad Unified                       1
Holtville Unified                     1
Cuyama Joint Unified                  1
Waterford Unified                     1
Pacific Grove Unified                 1
Sunol Glen Unified                    1
Woodland Joint Unified                1
Tahoe-Truckee Unified                 1
Dixon Unified                         1
Princeton Joint Unified               1
Muroc Joint Unified                   1
Mammoth Unified                       1
Cloverdale Unified                    1
Shoreline Unified                     1
Sonoma Valley Unified                 1
Denair Unified                        1
North Monterey County Unified         1
Davis Joint Unified                   1
Firebaugh-Las Deltas Unified          1
Riverdale Joint Unified               1
Name: count, dtype: int64

In [ ]:
df.nunique()

ViewYN                              2
WaterfrontYN                        1
BasementYN                          1
PoolPrivateYN                       2
ClosePrice                       5794
ListAgentFirstName               6177
ListAgentLastName               13460
Latitude                        46216
Longitude                       46437
PropertyType                        1
LivingArea                       3789
CoListOfficeName                 1864
ListAgentFullName               23786
FireplacesTotal                     0
AssociationFeeFrequency             4
AboveGradeFinishedArea              0
TaxAnnualAmount                     0
CountyOrParish                     27
ElementarySchool                 1013
AttachedGarageYN                    2
ParkingTotal                       35
BuilderName                       718
PropertySubType                     1
SubdivisionName                  4858
BathroomsTotalInteger               6
City                              739
TaxYear                             0
BuildingAreaTotal                1044
BedroomsTotal                       5
ElementarySchoolDistrict            0
CoveredSpaces                       0
MiddleOrJuniorSchool              543
FireplaceYN                         2
Stories                             2
HighSchool                        440
Levels                             11
NewConstructionYN                   2
GarageSpaces                        9
HighSchoolDistrict                374
PostalCode                       1134
AssociationFee                   1030
LotSizeSquareFeet               11487
MiddleOrJuniorSchoolDistrict        0
SalesTaxRate                       31
UnemploymentRate                    3
MortgageRate30Fixed                 6
FedInterestRate                     2
CPI                                 6
Age                               149
LotDensity                      43560
FlooringType                       11
SchoolDistrict                    277
dtype: int64

Our research goal is the model that will use only features that are available to an end user interested in estimating the current value of any property, regardless of whether it is for sale. We will take out the features that are not related, and there are over 30% missing values.

In [ ]:
df = df.drop(columns=[
   'WaterfrontYN', 'BasementYN', 'ListAgentFirstName', 'ListAgentLastName', 'PropertyType',
    'CoListOfficeName', 'ListAgentFullName', 'FireplacesTotal', 'AssociationFeeFrequency',
    'AboveGradeFinishedArea', 'TaxAnnualAmount', 'ElementarySchool',
    'BuilderName', 'PropertySubType', 'SubdivisionName', 'TaxYear', 'BuildingAreaTotal',
    'ElementarySchoolDistrict', 'CoveredSpaces', 'MiddleOrJuniorSchool', 'HighSchool', 'Levels',
    'HighSchoolDistrict', 'PostalCode', 'AssociationFee', 'MiddleOrJuniorSchoolDistrict'
    ])

Let's download this dataset.

In [ ]:
df.shape

(47560, 26)

In [ ]:
import google.colab.files as files

df.to_csv("cleaned_data_dummies.csv", index=False)
files.download("cleaned_data_dummies.csv")